apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: brewz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/f5devcentral/spa-demo-app-api:sha-3438ace
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: mongodb
            - name: INVENTORY_URL
              value: http://inventory:8002
            - name: RECOMMENDATIONS_URL
              value: http://recommendations:8001
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: brewz
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: api