apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: brewz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: ghcr.io/f5devcentral/spa-demo-app-inventory:sha-3438ace
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: brewz
spec:
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: inventory