apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
  namespace: brewz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers:
        - name: recommendations
          image: ghcr.io/f5devcentral/spa-demo-app-recommendations:sha-3438ace
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations
  namespace: brewz
spec:
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: recommendations