apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
  namespace: brewz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
        - name: spa
          image: ghcr.io/f5devcentral/spa-demo-app-spa:sha-3438ace
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spa
  namespace: brewz
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: spa